# Generated by Django 4.0.6 on 2022-08-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
