# Generated by Django 4.0.6 on 2022-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazin', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Magazin.tag'),
        ),
    ]
